data:
  dataset: vsl_400
  modality: rgb
  subset: cam_1
  data_dir: data/processed/vsl_400
  transform:
    horizontal_flip_prob: 0.5
    aug_type: augmix
    aug_paras:
      magnitude: 3
      alpha: 1.0
      width: 5
      depth: -1
    sample_rate: 2
  fps: 30
  debug: False
model:
  arch: swin3d_s
  pretrained: DEFAULT
  num_frozen_layers: 0
  num_frames: 16
training:
  run_name: swin3d_s_v2.0
  learning_rate: 0.001
  weight_decay: 0.02
  num_train_epochs: 30
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 1
  metric_for_best_model: accuracy
  # report_to: wandb
  push_to_hub: True
  hub_model_id: vsltranslation    # Only enter organization/account name