data:
  dataset: vsl_98
  modality: pose
  # subset: cam_1
  data_dir: vsltranslation/vsl_98
  transform:
    bone_stream: False
    motion_stream: True
  fps: 30
  debug: False
evaluation:
  arch: sl_gcn
  pretrained: vsltranslation/test_sl_gcn_joint_motion
  eval_set: test
  push_to_hub: True