model:
  arch: dsta_slr
  pretrained: vsltranslation/test_dsta_slr_joint_motion
inference:
  source: data/processed/vsl_400/cam_1/000000.mp4
  output_dir: demo/run_1
  use_onnx: True
  show_skeleton: True
  visualize: True
  bone_stream: False
  motion_stream: True