model:
  arch: sl_gcn
  pretrained: vsltranslation/test_sl_gcn_bone
inference:
  source: data/processed/vsl_400/cam_1/000000.mp4
  output_dir: demo/run_1
  use_onnx: True
  show_skeleton: True
  visualize: True
  bone_stream: True
  motion_stream: False